# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Kevin's Room
subtitle: 一个逼格的程序猿、码农。
description: "用心关注 细心聆听 努力做好每一天"
author: Shaojun Liu
email: liu785029095@gmail.com
language: zh-Hans # zn-CN
timezone:
favicon: /favicon.ico
# 站点起始时间
since: 2015
# 访客数统计
counter: true
# ---------------------------------------------
# 社交链接，将在侧栏中显示
#----------------------------------------------
# Social Icons
social_icons:
  enable: true
  # Icon Mappings
  GitHub: github
  Twitter: twitter
  Weibo: weibo
  Email: envelope
  ZhiHu: zhihu
social:
  GitHub: http://github.com/liushaojun
  Twitter: your-twitter-url
  Weibo: http://www.weibo.com/u/2525006730/home
  # DouBan: your-douban-url
  ZhiHu: http://www.zhihu.com/people/liu-shao-jun-14
  Email: mailTo:liushaojunvip@sina.com
# 配置代码高亮
highlight:
  enable: true
  backtick_code_block: true
  line_number: true
  tab_replace:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://liushaojun.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
# Category & Tag
default_category: uncategorized
category_map:
tag_map:
  archive: 1
  category: 1
  tag: 1

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

index_generator:
  per_page: 10

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10
# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: next #modernist


# MathJax Support
mathjax:


# Swiftype Search API Key
swiftype_key: 3dArsRm2N87ztbgueLCQ

# Baidu Analytics ID
baidu_analytics: 9608b1a7bcbbcaeb58d4ec9843ee2a77

# Duoshuo ShortName
duoshuo_shortname: liushaojun
# 多说热评文章
duoshuo_hotartical: true
# Disqus
#disqus_shortname:

# Share
jiathis: false

# Share
duoshuo_share: true

links_title: Links
# links
links:
  MacTalk: http://macshuo.com/
  LongShao: http:/jinyunlong.github.io/
  TouTiao: http://toutiao.io/
  StackOverflow: http://stackoverflow.com/
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
#google_site_verification:


# Google Analytics
#google_analytics:


# Make duoshuo show UA
# user_id must NOT be null when admin_enable is true!
# you can visit http://dev.duoshuo.com get duoshuo user id.
# duoshuo_info:
#   ua_enable: true
#   admin_enable: false
#   user_id: 0
  #admin_nickname: ROOT


# Facebook SDK Support.
# https://github.com/iissnan/hexo-theme-next/pull/410
facebook_sdk:
  enable: false
  app_id:       #<app_id>
  fb_admin:     #<user_id>
  like_button:  #true
  webmaster:    #true

# Deployment
## Docs: http://hexo.io/docs/deployment.html
#
#Plugins
plugins:
- hexo-generator-feed
- hexo-generator-sitemap
#feed sitemap
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
sitemap:
  path: sitemap.xml

deploy:
  type: git
  repository: 
    github: https://github.com/liushaojun/liushaojun.github.io.git,master
    gitcafe: git@gitcafe.com:liushaojun/liushaojun.git,gitcafe-pages

